### ISSUE TITLE
ModuleNotFoundError: No module named 'Crypto'

### ISSUE THREAD

**Issue by a2nt** [goodix-fp-linux-dev/goodix-fp-dump#40]
Looks like a python module is missing
```
(.venv) darkmoon :: ~/goodix-fp-dump ‹master› # sudo python3 run_5385.py                                 
Traceback (most recent call last):
  File "/root/goodix-fp-dump/run_5385.py", line 1, in <module>
    import driver_53x5
  File "/root/goodix-fp-dump/driver_53x5.py", line 7, in <module>
    import Crypto.Hash.SHA256
ModuleNotFoundError: No module named 'Crypto'

(.venv) darkmoon :: ~/goodix-fp-dump ‹master› # python --version                                     
Python 3.11.8

```

**Comment by vi5vi5vi5** [comment]
Try 2 install "PyCrypto" or "PyCryptodome"

**Comment by NameeLesS** [comment]
You have to use venv python try `sudo .venv/bin/python ./run_5385.py`

**Comment by pol2095** [comment]
using `sudo .venv/bin/python ./run_5385.py`, I have this message error :
`AttributeError: module 'Crypto' has no attribute 'Random'`
Thanks

**Comment by egormanga** [comment]
- See: https://github.com/goodix-fp-linux-dev/goodix-fp-dump/issues/51#issuecomment-2627524273.
