### ISSUE TITLE
ValueError: Invalid OTP has occured on run_521d.py

### ISSUE THREAD

**Issue by KenchanPrfm** [goodix-fp-linux-dev/goodix-fp-dump#41]
0. install python-pyusb and python-spidev.
1. run python script.
2. run usbreset.out.
3. run python script.
4. I got following errror.

```read_otp()
Traceback (most recent call last):
  File "/home/k2/GitHub/goodix-521d-explanation/goodix-fp-dump/run_521d.py", line 3, in <module>
    driver_52xd.main(0x521d)
  File "/home/k2/GitHub/goodix-521d-explanation/goodix-fp-dump/driver_52xd.py", line 351, in main
    run_driver(device)
  File "/home/k2/GitHub/goodix-521d-explanation/goodix-fp-dump/driver_52xd.py", line 134, in run_driver
    raise ValueError("Invalid OTP")
ValueError: Invalid OTP
```

**Comment by mpi3d** [comment]
Driver is unstable and not ready
