### ISSUE TITLE
ModuleNotFoundError: No module named 'usb'

### ISSUE THREAD

**Issue by ItzzInfinity** [goodix-fp-linux-dev/goodix-fp-dump#42]
After Running ` sudo python3 run_5503.py` I am getting this error 

> Traceback (most recent call last):
>   File "/home/itzzinfinity/goodix-fp-dump/run_5110.py", line 1, in <module>
>     import driver_51x0
>   File "/home/itzzinfinity/goodix-fp-dump/driver_51x0.py", line 7, in <module>
>     import crcmod
> ModuleNotFoundError: No module named 'crcmod'
> 

Tried to install **crcmod** independently by `sudo pip3 install crcmod` now I am getting 

> Traceback (most recent call last):
  File "/home/itzzinfinity/goodix-fp-dump/run_5503.py", line 1, in <module>
    import driver_5503
  File "/home/itzzinfinity/goodix-fp-dump/driver_5503.py", line 12, in <module>
    import goodix
  File "/home/itzzinfinity/goodix-fp-dump/goodix.py", line 3, in <module>
    import usb
ModuleNotFoundError: No module named 'usb'

Although `sudo pip3 install usb` did not work for me

**Comment by benyaminl** [comment]
you need to run the activate as root, then after that you need to install the requirement, make sure the gcc build is working as it should be and show no error. Then you can run the package... 

It also needs some other things like `git submodule init` then `git submodule update`, before you run it.

**Comment by LagrangeH** [comment]
I had this problem also with `periphery` and `spidev`

This helped me:

```bash
sudo apt install python3-usb python3-crcmod python3-periphery python3-spidev
```

And it finally ran!

```
.venv ❯ sudo python3 run_55b4.py        
#######################################################
This program might break your device.
Consider that it may flash the device firmware.
Continue at your own risk.
But don't hold us responsible if your device is broken!
Don't run this program as part of a regular process.
#######################################################
Type 9122 to continue and confirm that you are not a bot
```

**Comment by MetalParsley753** [comment]
I have the same issue with "usb" but none of that helped. Since I am using arch the apt isn't any use so I tried pacman and yay but didn't find any thing. I found one on pip and it was installed for usb but that didn't help. I am also running it in a python virtual environment. The deice I am using is 538d. Here is the output:
```
Traceback (most recent call last):
  File "/home/daniels/goodix-fp-dump/run_538d.py", line 1, in <module>
    import driver_53xd
  File "/home/daniels/goodix-fp-dump/driver_53xd.py", line 9, in <module>
    import goodix
  File "/home/daniels/goodix-fp-dump/goodix.py", line 3, in <module>
    import usb
ModuleNotFoundError: No module named 'usb'
```

**Comment by egormanga** [comment]
- See: https://github.com/goodix-fp-linux-dev/goodix-fp-dump/issues/51#issuecomment-2627524273.
